# Generated by Django 4.2.18 on 2025-02-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Final', 'final')], default='draft', max_length=10),
        ),
    ]
